name = "chopatech-site"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./"
exclude = ["node_modules/**", "worker.js"]

[ai]
binding = "AI"