name = "chopatech-site"
main = "src/index.js"
compatibility_date = "2026-05-20"

[[d1_databases]]
binding = "DB"
database_name = "myschoolportal-db"
database_id = "c0b8e0a2-edfb-4b71-a6be-b0d2e2df076e"
remote = true